version: 2.1

orbs:
  # https://circleci.com/orbs/registry/orb/circleci/aws-s3
  aws-s3: circleci/aws-s3@1.0.11

#
# Reusable definitions
#
references:
  # Basic defaults that most jobs will need.
  defaults: &defaults
    working_directory: ~/ci-build
    docker:
      - image: circleci/node:12.14.1

  # Filter to run a job on builds for the release branch only.
  filter_only_release_branch: &filter_only_release_branch
    filters:
      branches:
        only:
          - /^release$/

  # Filter to run a job on tagged releases.
  # https://circleci.com/docs/2.0/workflows/#using-regular-expressions-to-filter-tags-and-branches
  # https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag
  release_tag_filter: &release_tag_filter
    filters:
      tags:
        only: /^v[0-9.]+.*/
      branches:
        ignore: /.*/

  # Attach the root workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: '.'


#
# Jobs
#
jobs:
  setup:
    <<: *defaults
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - ts-design-tokens-yarn-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - ts-design-tokens-yarn-deps-{{ .Branch }}
            - ts-design-tokens-yarn-deps-release
            - ts-design-tokens-yarn-deps-
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --non-interactive
      - run:
          name: Versions
          command: |
            echo "Yarn version: "
            yarn --version
      - save_cache:
          name: Save Yarn Cache
          key: ts-design-tokens-yarn-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  lint:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Lint
          command: yarn run lint:ci
  build:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Build Project
          command: yarn run build
      - store_artifacts:
          path: /home/circleci/.npm/_logs/
          destination: ~/npm_logs/
      - persist_to_workspace:
          root: .
          paths:
            - ./build/*
  publish_library:
    <<: *defaults
    steps:
      - *attach_workspace
      - add_ssh_keys
      - run:
          name: Publish Tokens
          command: npx semantic-release


#
# Workflows
#
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - lint:
          requires:
            - setup
      - build_demos:
          requires:
            - build
      - publish_library:
          <<: *filter_only_release_branch
          requires:
            - build
            - build_demos
            - lint
            - test
